"""updated CRUD METHODS

Revision ID: e0165235faf2
Revises: 5b0c7d4d2a09
Create Date: 2024-03-10 10:13:59.195418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0165235faf2'
down_revision = '5b0c7d4d2a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
